// const fs = require('load-json-file');
// let rawdata = fs.readFileSync('db.json');
console.log("dnajkdbajk");
news: [];
technical: [];
training: [];
hr: [];
publicity: [];
media: [];
fr: [];
events: [];
